version: "3.8"

services:
    nginx:
        build:
            context: ./docker/dockerfiles
            dockerfile: nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: ${APP_NAME}_nginx
        expose:
            - "80/tcp"
        ports:
            - "8000:80"
        volumes:
            - ./docker/configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/html:delegated
        depends_on:
            - php
            - db
        networks:
            - zaryad

    php:
        build:
            context: ./docker/dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: ${APP_NAME}_php
        volumes:
            - ./:/var/www/html:delegated
        networks:
            - zaryad

    db:
        image: mariadb:11.1.2
        container_name: ${APP_NAME}_db
        restart: unless-stopped
        tty: true
        expose:
            - "3306/tcp"
        ports:
            - "3306:3306"
        volumes:
            - ./docker/database:/var/lib/mysql
        environment:
            - MARIADB_USER=${DB_USERNAME}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MARIADB_DATABASE=${DB_DATABASE}
        depends_on:
            - phpmyadmin
        networks:
            - zaryad

    phpmyadmin:
        image: phpmyadmin:5
        container_name: ${APP_NAME}_phpmyadmin
        restart: always
        expose:
            - "80/tcp"
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=${DB_HOST}
            - UPLOAD_LIMIT=1024M
        networks:
            - zaryad

    npm:
        image: node:current-alpine
        container_name: ${APP_NAME}_npm
        volumes:
            - ./:/var/www/html
        expose:
            - "3000/tcp"
            - "3001/tcp"
            - "5173/tcp"
        ports:
            - "3000:3000"
            - "3001:3001"
            - "5173:5173"
        working_dir: /var/www/html
        entrypoint: [ 'npm' ]
        networks:
            - zaryad

networks:
    zaryad:
        name: zaryad
        driver: bridge
